# https://just.systems

default:
    echo 'Hello, world!'

[group('python')]
install:
    python -m pip install --upgrade pip
    python -m pip install -e .

alias i := install

[group('django')]
run:
    python manage.py runserver

[group('django')]
migrate:
    python manage.py migrate
